### ISSUE TITLE
Функциональные требования

### ISSUE THREAD

**Issue by paulmixxx** [Ignasiya/chtune-social#1]
@Ignasiya давай опишем функциональные требования к приложению. Представь, что мы стартаперы из силиконовой долины. У нас нет php, laravel, vue, docker и прочих технологий в данный момент. Мы еще не написали ни строчки кода. У нас есть только лист бумаги, ручка и идеи. Какие функции/идеи/фичи мы хотим реализовать. Повторюсь, речь не про технологии, а про то, **что может делать пользователь** в нашем приложении, какие функции ему доступны.

**Comment by Ignasiya** [comment]
Если правильно понимаю, такое описание в текстовой части проекта подойдет: 

- Регистрация и аутентификация пользователей:
пользователи должны иметь возможность создать аккаунт с помощью уникального имени пользователя, адреса электронной почты и пароля;
вход в систему должен осуществляться посредством ввода учетных данных;
должна быть предусмотрена возможность восстановления пароля.

- Профили пользователей:
каждый пользователь должен иметь профиль, на котором можно указать фотографию, обложку и другие данные;
пользователи должны иметь возможность редактировать свой профиль.

- Создание и редактирование постов:
пользователи должны иметь возможность создавать посты, содержащие текст, ссылки на другие источники в сети, фотографии, видео или другие медиафайлы;
должна быть предусмотрена возможность просмотра, редактирования, закрепления и удаления постов.

- Комментирование постов:
пользователи должны иметь возможность комментировать посты других пользователей;
должна быть предусмотрена возможность редактирования и удаления комментариев.

- Взаимодействие пользователей:
пользователи должны иметь возможность подписываться на других пользователей и получать их обновления в ленте;
должна быть возможность оценивания постов и комментариев, а также отмечания их как понравившихся;
должна быть предусмотрена возможность уведомления пользователей о новых событиях, таких как упоминания и комментарии.
- Создание группы:
пользователи должны иметь возможность создавать группы с определенной тематикой или интересами;
должна быть предусмотрена возможность указания типа группы: публичный (доступен для всех) или с запросом на вход (пользователи должны отправить запрос на вступление в группу);
пользователь, создавший группу, должен автоматически стать администратором группы.

- Профили группы:
каждая группа должна иметь свой собственный профиль с описанием, обложкой и аватаркой;
должна быть возможность редактирования профиля группы администратором группы.

- Роли администратора и пользователей в группе:
группы должны поддерживать роли администратора и пользователей;
администраторы должны иметь права для управления группой и редактирования контента;
пользователи группы должны иметь возможность просматривать контент, комментировать и оценивать посты внутри группы.

- Редактирование группы:
администраторы группы должны иметь возможность редактировать основную информацию о группе, такую как описание и тематику.
также должна быть предусмотрена возможность изменения обложки и аватарки группы.

- Глобальный поиск:
должна быть предусмотрена возможность поиска постов пользователей и групп.
отдельно поиск должен включать возможность поиска по подписчикам, на кого подписан пользователь и членам группы.

**Comment by paulmixxx** [comment]
Отлично! То, что нужно!
Давай создадим PR и добавим эти требования в Readme.md.
Чтобы Readme не раздувался, можно создать папку docs в корне и положить туда полное описание, а в readme можно либо коротко перечислить пунктами и оставить ссылку на полное описание, либо только ссылку на полное описание оставить.

**Comment by Ignasiya** [comment]
Спасибо за по шаговое разъяснение, надеюсь правильно вышло: https://github.com/Ignasiya/chtune-social/pull/2

**Comment by paulmixxx** [comment]
Вышло отлично!
