### ISSUE TITLE
Фикстуры

### ISSUE THREAD

**Issue by paulmixxx** [Ignasiya/chtune-social#10]
Первое, что бросилось в глаза после разворачивания проекта, это то, что он пустой.
Используя механизм посевов (seeds) и fakerphp/faker необходимо наполнить проект фикстурами. Предлагаю добавить не менее 100 пользователей, у каждого пользователя не менее 10 постов, комментариев и остальных моделей. В общем должно быть ощущение, что это настоящая социальная сеть. Можно даже подумать над тем, чтобы взять реальные данные с vk, как вариант. 

Наполнение фикстур должно происходить в момент выполнения команды init.

**Comment by Ignasiya** [comment]
Понял, как раз потренируюсь в наполнении, всё руки не доходили разобраться 🤔

**Comment by Ignasiya** [comment]
Привет, немного затянул с выполнением задачи )) Получилось сыро и мне кажется прямо в лоб, наверняка есть красивое решение. Можешь подсказать в правильную сторону иду с фикстурами или все плохо? https://github.com/Ignasiya/chtune-social/pull/11

**Comment by Ignasiya** [comment]
Внес изменения, вроде получше стало ))
