### ISSUE TITLE
Автоматизация развертывания с помощью утилиты Make

### ISSUE THREAD

**Issue by paulmixxx** [Ignasiya/chtune-social#3]
В целом проект неплохо подготовлен к развертыванию для локальной разработки, но можно улучшить. Есть такая утилита Make. С помощью нее можно автоматизировать развертывание проекта полностью. Для этого необходимо создать Makefile и добавить в него необходимые команды (target).
Пример можно глянуть в https://github.com/paulmixxx/rabbit-cms-module-blog/blob/master/Makefile

Давай для начала добавим такие команды:
* init - полная установка проекта с нуля. Результат: после выполнения данной команды не нужно никаких дополнительных действий, просто приступаем к работе с проектом
* up - запускает контейнеры
* down - удаляет контейнеры
* restart: down up
* composer-install - устанавливает все зависимости
* app - заходим внутрь контейнера php
* db - заходим внутрь контейнера mysql

Также в Readme добавить описание команд в виде таблицы
| Command | Description |
| :--- | :---: |
| make up | Запустить контейнеры |
| make down | Удалить контейнеры |

Создать PR с правками.

**Comment by Ignasiya** [comment]
Спасибо, классная вещь makefile: https://github.com/Ignasiya/chtune-social/pull/4

**Comment by Ignasiya** [comment]
Привет, внес правки. Протупил с .env - оказывается docker подтягивает из своего environment MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD вместо файла .env.
